	Version "0.0.0.1"
	PluginName "Test"
	Author "David Harvey"
	AuthorLink "www.davethehat.com"
	Description "Test and assertions library for Sibelius ManuScript Plugin Development"
	PluginDate "February 2015"
	Copyright "(c) David Harvey 2015"
	License "ISC License"
	LicenseLink "http://www.isc.org/downloads/software-support-policy/isc-license/"
